apiVersion: apps/v1
kind: Deployment
metadata:
  name: lunatic-cat
  namespace: lunatic-cat
spec:
  selector:
    matchLabels:
      app: lunatic-cat
  replicas: 1
  template:
    metadata:
      labels:
        app: lunatic-cat
    spec:
      containers:
      - image: lunaticcat/lunatic.cat:latest
        name: lunatic-cat
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: lunatic-cat
  namespace: lunatic-cat
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: lunatic-cat
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: letsencrypt-prod
  namespace: lunatic-cat
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: k8s@lunatic.cat
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: nginx
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: lunatic-cat
  namespace: lunatic-cat
  annotations:
    kubernetes.io/ingress.class: "nginx"
    certmanager.k8s.io/issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - lunatic.cat
    secretName: lunatic-cat-ing-tls
  rules:
  - host: lunatic.cat
    http:
      paths:
      - path: /
        backend:
          serviceName: lunatic-cat
          servicePort: 80